/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoButton {
        /**
          * Example property to show visual differences in the Preview
         */
        "type": "button" | "link";
    }
}
declare global {
    interface HTMLDemoButtonElement extends Components.DemoButton, HTMLStencilElement {
    }
    var HTMLDemoButtonElement: {
        prototype: HTMLDemoButtonElement;
        new (): HTMLDemoButtonElement;
    };
    interface HTMLElementTagNameMap {
        "demo-button": HTMLDemoButtonElement;
    }
}
declare namespace LocalJSX {
    interface DemoButton {
        /**
          * Example event to show event handling (actions) in the Preview
         */
        "onClicked"?: (event: CustomEvent<void>) => void;
        /**
          * Example property to show visual differences in the Preview
         */
        "type"?: "button" | "link";
    }
    interface IntrinsicElements {
        "demo-button": DemoButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-button": LocalJSX.DemoButton & JSXBase.HTMLAttributes<HTMLDemoButtonElement>;
        }
    }
}
